name: Publish FE
description: Build and deploy webapp
branding:
  icon: package
  color: blue
inputs:
  aws-access-key:
    description: 'AWS Secret Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region of the S3 and CloudFront resources'
    required: true
  aws-s3-name:
    description: 'Name of the AWS S3 bucket'
    required: true
  aws-cloudfront-name:
    description: 'Name of the AWS S3 bucket'
    required: true
  slack-channel:
    description: 'Name of the Slack channel used for CI alerts'
    required: true
  slack-token:
    description: 'Token for Slack integration'
    required: true
  build-command:
    description: 'Command used to build the application [ yarn | npm ] (default: yarn)'
    required: false
    default: 'yarn'
  app-envs:
    description: 'Environment variables passed to the application'
    required: false
    default: ''
  build-path:
    description: 'Local path of the build (default: build)'
    required: false
    default: 'build'
  node-version:
    description: 'NodeJS required version (default: 16.x)'
    required: false
    default: '16.x'
runs:
  using: "composite"
  steps:  
    - name: Notify Slack Start
      id: notify-slack-start
      uses: cristi-mb/slack-notify@1.2
      with:
        message-type: 'start'
        slack-channel: ${{ inputs.slack-channel }}
        slack-bot-token: ${{ inputs.slack-token }}
        
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3.2.0

    - name: Setup Nodejs
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies (yarn)
      if: inputs.build-command == 'yarn'
      id: node-cache-yarn
      uses: actions/cache@v3.0.11
      with:
        path: |
          **/node_modules
        key: dev-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
    - name: Cache dependencies (npm)
      if: inputs.build-command == 'npm'
      id: node-cache-npm
      uses: actions/cache@v3.0.11
      with:
        path: |
          **/node_modules
        key: dev-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies (yarn)
      if: inputs.build-command == 'yarn' && steps.node-cache.outputs.cache-hit != 'true'
      id: install-dependencies-yarn
      run: yarn install --pure-lockfile
      shell: bash
      
    - name: Install dependencies (npm)
      if: inputs.build-command == 'npm' && steps.node-cache.outputs.cache-hit != 'true'
      id: install-dependencies-npm
      run: npm ci
      shell: bash

    - name: Set envs
      run: |
        for e in $(echo ${{ inputs.app-envs }} | cut -d ' ' -f 1-); do
          key=$(echo $e | cut -d '=' -f 1)
          value=$(echo $e | cut -d '=' -f 2)
          echo "$key=$value" >> $GITHUB_ENV
        done
      shell: bash

    - name: Build (yarn)
      if: inputs.build-command == 'yarn'
      id: build-yarn
      run: yarn build
      env:
        CI: false
      shell: bash
    
    - name: Build (npm)
      if: inputs.build-command == 'npm'
      id: build-npm
      run: npm run build
      env:
        CI: false
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy static site to S3
      id: deploy
      run: ls -l && aws s3 sync ${{ inputs.build-path }} s3://${{ inputs.aws-s3-name }} --delete
      shell: bash

    - name: Invalidate CloudFront cache
      id: invalidate-cache
      run: |
        #!/usr/bin/env bash
        set -eou pipefail
        CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, '${{ inputs.aws-cloudfront-name }}')].Id | [0]" | tr -d \")
        echo "Clearing cache for ${CF_DIST_ID}..."
        CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
        while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
          echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
          sleep 5
        done
      shell: bash

    - name: Notify Slack Result
      if: always()
      uses: cristi-mb/slack-notify@1.2
      with:
        message-type: 'results'
        slack-channel: ${{ inputs.slack-channel }}
        slack-bot-token: ${{ inputs.slack-token }}
        message-ts: ${{ steps.notify-slack-start.outputs.message-ts }}
        steps-context: "'${{ toJson(steps) }}'"
